import React from "react";
import Menu from "./components/Menu";
import {BrowserRouter as Router, Switch, Route} from "react-router-dom";
import Home from "./components/Home";
import Contact from "./components/Contact";
import Music from "./components/Music";
import Tracks from "./util/Tracks";
import Pnf from "./components/Pnf";
/**
 * In every hook there will be a provider and consumer
 * providers take input
 * consumers generate output
 * the whole module is the router. it has provider that takes input and the output is generated by the consumer
 * BrowserRouter has a Router.provier and a Router.consumer
 * Each component will have to pass through the router
 * We will switch between the components using switch
 * 
 *                 Router
 *                   |
 *                   V
 *         ------React App-------
 *         |         |          |
 *         V         V          V
 *       Music     Home      Contact
 * 
 */
function App() {
  return (
    <Router>
      <Menu/>

      <Switch>
        <Route exact path="/" component={Home} />
        <Route exact path="/home" component={Home} />
        <Route exact path="/music" component={Music} />
        <Route exact path="/contact" component={Contact} />
        <Route exact path="/tracks/:id" component={Tracks}/>
        <Route component={Pnf}/>
      </Switch>
    </Router>
  );
}

export default App;
